LOAD DATA INFILE 'C:/Users/lhaverkamp/git/ccb-migration/migration/src/main/resources/db/data/address.csv'
	INTO TABLE address
	FIELDS
		TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
	LINES
		TERMINATED BY '\n'
	IGNORE 1 LINES
	(
		ADDRESSID,
		XREFID,
		@ISPRIMARY,
		ADDRESS1,
		@ADDRESS2,
		CITY,
		STATE,
		ZIPCODE,
		@COUNTRYID,
		@CARRIERROUTE,
		@COUNTYCODE,
		@DESCRIPTION,
		@MAPPAGE,
		@MAPCOL,
		@MAPROW,
		@BEGINDATE,
		@ENDDATE,
		@ISRECURRING,
		@LASTROLOCHG,
		@NOTEID,
		@CREATIONDATETIME,
		@REVISIONDATETIME,
		DELIVERYPOINT,
		CHECKDIGIT,
		LOTNUMBER,
		@LASTCASS
	)
	SET ISPRIMARY = IF(@ISPRIMARY = 'true', TRUE, FALSE),
		ADDRESS2 = NULLIF(@ADDRESS2, ''),
		COUNTRYID = NULLIF(@COUNTRYID, ''),
		CARRIERROUTE = NULLIF(@CARRIERROUTE, ''),
		DESCRIPTION = NULLIF(@DESCRIPTION, ''),
		MAPPAGE = NULLIF(@MAPPAGE, ''),
		MAPCOL = NULLIF(@MAPCOL, ''),
		MAPROW = NULLIF(@MAPROW, ''),
		BEGINDATE = STR_TO_DATE(NULLIF(@BEGINDATE, '0100-01-03 00:00:00.0'), '%Y-%m-%d %H:%i:%S.%x'),
		ENDDATE = STR_TO_DATE(NULLIF(@ENDDATE, '9999-12-31 00:00:00.0'), '%Y-%m-%d %H:%i:%S.%x'),
		ISRECURRING = IF(@ISRECURRING = 'true', TRUE, FALSE),
		LASTROLOCHG = STR_TO_DATE(NULLIF(@LASTROLOCHG, ''), '%Y-%m-%d %H:%i:%S.%x'),
		NOTEID = NULLIF(@NOTEID, 0),
		CREATIONDATETIME = STR_TO_DATE(@CREATIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		REVISIONDATETIME = STR_TO_DATE(@REVISIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		LASTCASS = STR_TO_DATE(NULLIF(@LASTCASS, ''), '%Y-%m-%d %H:%i:%S.%x')
