LOAD DATA INFILE 'C:/Users/lhaverkamp/git/ccb-migration/migration/src/main/resources/db/data/note.csv'
	INTO TABLE note
	FIELDS
		TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
	LINES
		TERMINATED BY '\n'
	IGNORE 1 LINES
	(
		NOTEID,
		NOTE,
		@CREATIONDATETIME,
		@REVISIONDATETIME
	)
	SET CREATIONDATETIME = STR_TO_DATE(@CREATIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		REVISIONDATETIME = STR_TO_DATE(@REVISIONDATETIME, '%Y-%m-%d %H:%i:%S.%x')