LOAD DATA INFILE 'C:/Users/lhaverkamp/git/ccb-migration/migration/src/main/resources/db/data/phone.csv'
	INTO TABLE phone
	FIELDS
		TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
	LINES
		TERMINATED BY '\n'
	IGNORE 1 LINES
	(
		PHONEID,
		XREFID,
		TYPE,
		@AREACODE,
		@NUMBER,
		EXTENSION,
		@ISLISTED,
		DESCRIPTION,
		@NOTEID,
		@CREATIONDATETIME,
		@REVISIONDATETIME
	)
	SET AREACODE = TRIM(@AREACODE),
		NUMBER = TRIM(REPLACE(@NUMBER, '-', '')),
		ISLISTED = IF(@ISLISTED = 'true', TRUE, FALSE),
		NOTEID = NULLIF(@NOTEID, 0),
		CREATIONDATETIME = STR_TO_DATE(@CREATIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		REVISIONDATETIME = STR_TO_DATE(@REVISIONDATETIME, '%Y-%m-%d %H:%i:%S.%x')

