LOAD DATA INFILE 'C:/Users/lhaverkamp/git/ccb-migration/migration/src/main/resources/db/data/death.csv'
	INTO TABLE death
	FIELDS
		TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
	LINES
		TERMINATED BY '\n'
	IGNORE 1 LINES
	(
		DEATHID,
		IDTYPE,
		ID,
		DATEOFDEATH,
		NAMEOFDECEASED,
		RELATIONSHIP,
		@NOTEID,
		@CREATIONDATETIME,
		@REVISIONDATETIME
	)
	SET NOTEID = NULLIF(@NOTEID, 0),
		CREATIONDATETIME = STR_TO_DATE(@CREATIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		REVISIONDATETIME = STR_TO_DATE(@REVISIONDATETIME, '%Y-%m-%d %H:%i:%S.%x')
