LOAD DATA INFILE 'C:/Users/lhaverkamp/git/ccb-migration/migration/src/main/resources/db/data/contributor.csv'
	INTO TABLE contributor
	FIELDS
		TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
	LINES
		TERMINATED BY '\n'
	IGNORE 1 LINES
	(
		ENVELOPE,
		NEXTYEARENVELOPE,
		@PERSON1ID,
		@PERSON2ID,
		@ISSHARED,
		@NOTEID,
		@CREATIONDATETIME,
		@REVISIONDATETIME,
		@DONOTRENUMBER,
		ENVELOPENAME,
		P1FIRSTORNICKNAME,
		P1LASTNAME,
		P1SUFFIX,
		P2FIRSTORNICKNAME,
		P2LASTNAME,
		P2SUFFIX,
		STATEMENTNAME,
		EOI_ID,
		PREFERREDSTATEMENTMETHOD,
		@LASTSTATEMENTEMAILDATE
	)
	SET PERSON1ID = NULLIF(@PERSON1ID, 0),
		PERSON2ID = NULLIF(@PERSON2ID, 0),
		ISSHARED = IF(@ISSHARED = 'true', TRUE, FALSE),
		NOTEID = NULLIF(@NOTEID, 0),
		CREATIONDATETIME = STR_TO_DATE(@CREATIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		REVISIONDATETIME = STR_TO_DATE(@REVISIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		DONOTRENUMBER = IF(@DONOTRENUMBER = 'true', TRUE, FALSE),
		LASTSTATEMENTEMAILDATE = STR_TO_DATE(@LASTSTATEMENTEMAILDATE, '%Y-%m-%d %H:%i:%S.%x')
