LOAD DATA INFILE 'C:/Users/lhaverkamp/git/ccb-migration/migration/src/main/resources/db/data/contributionfund.csv'
	INTO TABLE contributionfund
	FIELDS
		TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
	LINES
		TERMINATED BY '\n'
	IGNORE 1 LINES
	(
		FUNDID,
		FUNDNUMBER,
		NAME,
		INCOMEACCOUNT,
		BANKACCOUNT,
		@ISPLEDGERENEWED,
		POSTING,
		@NOTEID,
		@CREATIONDATETIME,
		@REVISIONDATETIME,
		@USEFASB116,
		FASB116ACCOUNTID,
		POSTINGPLEDGED,
		@ISINACTIVE
	)
	SET ISPLEDGERENEWED = IF(@ISPLEDGERENEWED = 'true', TRUE, FALSE),
		NOTEID = NULLIF(@NOTEID, 0),
		CREATIONDATETIME = STR_TO_DATE(@CREATIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		REVISIONDATETIME = STR_TO_DATE(@REVISIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		USEFASB116 = IF(@USEFASB116 = 'true', TRUE, FALSE),
		ISINACTIVE = IF(@ISINACTIVE = 'true', TRUE, FALSE)
