LOAD DATA INFILE 'C:/Users/lhaverkamp/git/ccb-migration/migration/src/main/resources/db/data/contribution.csv'
	INTO TABLE contribution
	FIELDS
		TERMINATED BY ','
		OPTIONALLY ENCLOSED BY '"'
	LINES
		TERMINATED BY '\n'
	IGNORE 1 LINES
	(
		CONTRIBUTIONID,
		PLEDGEID,
		DATE,
		FUNDID,
		AMOUNT,
		PERSON1ID,
		@PERSON2ID,
		DESCRIPTION,
		@NOTEID,
		@CREATIONDATETIME,
		@REVISIONDATETIME,
		CHECKNUMBER,
		BATCHID,
		BATCHENTEREDBY,
		BATCHPOSTEDBY,
		@IS_EOI_OFFERING,
		RECURRENTOFFERINGID
	)
	SET PERSON2ID = NULLIF(@PERSON2ID, 0),
		NOTEID = NULLIF(@NOTEID, 0),
		CREATIONDATETIME = STR_TO_DATE(@CREATIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		REVISIONDATETIME = STR_TO_DATE(@REVISIONDATETIME, '%Y-%m-%d %H:%i:%S.%x'),
		IS_EOI_OFFERING = IF(@IS_EOI_OFFERING = 'true', TRUE, FALSE)