LOAD DATA INFILE '../csv/individual_export.csv'
INTO TABLE individual_export
FIELDS
	TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
LINES
	TERMINATED BY '\n'
IGNORE 1 LINES
(
	individual_id,
	family_id,
	@family_position,
	@limited_access_user,
	@prefix,
	@first_name,
	@middle_name,
	@last_name,
	@suffix,
	@campus,
	@email,
	@email_privacy_level,
	@general_communication,
	@area_of_town,
	@mailing_street,
	@mailing_city,
	@mailing_state,
	@mailing_zip,
	@mailing_carrier_route,
	@mailing_privacy_level,
	@mailing_latitude,
	@mailing_longitude,
	@contact_phone,
	@contact_phone_privacy_level,
	@home_phone,
	@home_phone_privacy_level,
	@work_phone,
	@work_phone_privacy_level,
	@mobile_phone,
	@mobile_phone_privacy_level,
	@fax,
	@fax_privacy_level,
	@pager,
	@pager_privacy_level,
	@emergency_phone,
	@emergency_phone_privacy_level,
	@emergency_contact_name,
	@birthday,
	@birthday_privacy_level,
	@anniversary,
	@anniversary_privacy_level,
	@gender,
	@gender_privacy_level,
	@giving_number,
	@marital_status,
	@marital_status_privacy_level,
	@home_area,
	@home_street,
	@home_city,
	@home_state,
	@home_zip,
	@home_privacy_level,
	@work_area,
	@work_street,
	@work_city,
	@work_state,
	@work_zip,
	@work_privacy_level,
	@other_area,
	@other_street,
	@other_city,
	@other_state,
	@other_zip,
	@other_privacy_level,
	@work_title,
	@school_name,
	@school_grade,
	@badge_queue,
	@allergies,
	@allergies_privacy_level,
	@salvation_date,
	@chat_aol,
	@chat_msn,
	@chat_icq,
	@my_website,
	@work_website,
	@favorite_radio_station,
	@military,
	@user_defined_text_1,
	@user_defined_text_2,
	@user_defined_text_3,
	@user_defined_text_4,
	@user_defined_text_5,
	@user_defined_text_6,
	@user_defined_text_7,
	@user_defined_text_8,
	@user_defined_text_9,
	@confirmation_verse,
	@email_work,
	@maiden_name,
	@user_defined_date_1,
	@user_defined_date_2,
	@user_defined_date_3,
	@first_communion,
	@confirmation,
	@baptism,
	@user_defined_pulldown_1,
	@user_defined_pulldown_2,
	@user_defined_pulldown_3,
	@elder,
	@newsletter,
	@confirmed,
	user_defined_privacy_level,
	my_fit_privacy_level,
	community_privacy_level,
	created_by,
	modified_by,
	@created_date,
	@modified_date,
	@age_bracket,
	@membership_start_date,
	@membership_end_date,
	@membership_type,
	@spiritual_maturity,
	@baptized,
	@listed,
	@inactive,
	@how_they_heard,
	@reason_left_church,
	@child_work_date_start,
	@child_work_date_end
)
SET 
	family_position = NULLIF(@family_position, ''),
	limited_access_user = IF(@limited_access_user = '', '0', @limited_access_user),
	prefix = NULLIF(@prefix, ''),
	first_name = NULLIF(@first_name, ''),
	middle_name = NULLIF(@middle_name, ''),
	last_name = NULLIF(@last_name, ''),
	suffix = NULLIF(@suffix, ''),
	campus = NULLIF(@campus, ''),
	email = NULLIF(@email, ''),
	general_communication = IF(@general_communication = 'Yes', TRUE, FALSE),
	area_of_town = NULLIF(@area_of_town, ''),
	mailing_street = NULLIF(@mailing_street, ''),
	mailing_city = NULLIF(@mailing_city, ''),
	mailing_state = NULLIF(@mailing_state, ''),
	mailing_zip = NULLIF(@mailing_zip, ''),
	mailing_carrier_route = NULLIF(@mailing_carrier_route, ''),
	mailing_latitude = NULLIF(@mailing_latitude, ''),
	mailing_longitude = NULLIF(@mailing_longitude, ''),
	contact_phone = NULLIF(@contact_phone, ''),
	home_phone = NULLIF(@home_phone, ''),
	work_phone = NULLIF(@work_phone, ''),
	mobile_phone = NULLIF(@mobile_phone, ''),
	fax = NULLIF(@fax, ''),
	pager = NULLIF(@pager, ''),
	emergency_phone = NULLIF(@emergency_phone, ''),
	emergency_contact_name = NULLIF(@emergency_contact_name, ''),
	birthday = STR_TO_DATE(NULLIF(@birthday, ''), '%b %d, %Y'),
	anniversary = STR_TO_DATE(NULLIF(@anniversary, ''), '%b %d, %Y'),
	gender = NULLIF(@gender, ''),
	giving_number = NULLIF(@giving_number, ''),
	marital_status = NULLIF(@marital_status, ''),
	home_area = NULLIF(@home_area, ''),
	home_street = IF(@home_street = 'Unknown', NULL ,NULLIF(@home_street, '')),
	home_city = NULLIF(@home_city, ''),
	home_state = NULLIF(@home_state, ''),
	home_zip = NULLIF(@home_zip, ''),
	work_area = NULLIF(@work_area, ''),
	work_street = NULLIF(@work_street, ''),
	work_city = NULLIF(@work_city, ''),
	work_state = NULLIF(@work_state, ''),
	work_zip = NULLIF(@work_zip, ''),
	other_area = NULLIF(@other_area, ''),
	other_street = NULLIF(@other_street, ''),
	other_city = NULLIF(@other_city, ''),
	other_state = NULLIF(@other_state, ''),
	other_zip = NULLIF(@other_zip, ''),
	work_title = NULLIF(@work_title, ''),
	school_name = NULLIF(@school_name, ''),
	school_grade = NULLIF(@school_grade, ''),
	badge_queue = NULLIF(@badge_queue, ''),
	allergies = NULLIF(@allergies, ''),
	salvation_date = STR_TO_DATE(NULLIF(@salvation_date, ''), '%b %d, %Y'),
	chat_aol = NULLIF(@chat_aol, ''),
	chat_msn = NULLIF(@chat_msn, ''),
	chat_icq = NULLIF(@chat_icq, ''),
	my_website = NULLIF(@my_website, ''),
	work_website = NULLIF(@work_website, ''),
	favorite_radio_station = NULLIF(@favorite_radio_station, ''),
	military = NULLIF(@military, ''),
	user_defined_text_1 = NULLIF(@user_defined_text_1, ''),
	user_defined_text_2 = NULLIF(@user_defined_text_2, ''),
	user_defined_text_3 = NULLIF(@user_defined_text_3, ''),
	user_defined_text_4 = NULLIF(@user_defined_text_4, ''),
	user_defined_text_5 = NULLIF(@user_defined_text_5, ''),
	user_defined_text_6 = NULLIF(@user_defined_text_6, ''),
	user_defined_text_7 = NULLIF(@user_defined_text_7, ''),
	user_defined_text_8 = NULLIF(@user_defined_text_8, ''),
	user_defined_text_9 = NULLIF(@user_defined_text_9, ''),
	confirmation_verse = NULLIF(@confirmation_verse, ''),
	email_work = NULLIF(@email_work, ''),
	maiden_name = NULLIF(@maiden_name, ''),
	user_defined_date_1 = STR_TO_DATE(NULLIF(@user_defined_date_1, ''), '%b %d, %Y'),
	user_defined_date_2 = STR_TO_DATE(NULLIF(@user_defined_date_2, ''), '%b %d, %Y'),
	user_defined_date_3 = STR_TO_DATE(NULLIF(@user_defined_date_3, ''), '%b %d, %Y'),
	first_communion = STR_TO_DATE(NULLIF(@first_communion, ''), '%b %d, %Y'),
	confirmation = STR_TO_DATE(NULLIF(@confirmation, ''), '%b %d, %Y'),
	baptism = STR_TO_DATE(NULLIF(@baptism, ''), '%b %d, %Y'),
	user_defined_pulldown_1 = NULLIF(@user_defined_pulldown_1, ''),
	user_defined_pulldown_2 = NULLIF(@user_defined_pulldown_2, ''),
	user_defined_pulldown_3 = NULLIF(@user_defined_pulldown_3, ''),
	elder = NULLIF(@elder, ''),
	newsletter = NULLIF(@newsletter, ''),
	confirmed = NULLIF(@confirmed, ''),
	created_date = STR_TO_DATE(@created_date, '%b %d, %Y'),
	modified_date = STR_TO_DATE(@modified_date, '%b %d, %Y'),
	age_bracket = NULLIF(@age_bracket, ''),
	membership_start_date = STR_TO_DATE(NULLIF(@membership_start_date, ''), '%b %d, %Y'),
	membership_end_date = STR_TO_DATE(NULLIF(@membership_end_date, ''), '%b %d, %Y'),
	membership_type = NULLIF(@membership_type, ''),
	spiritual_maturity = NULLIF(@spiritual_maturity, ''),
	baptized = IF(@baptized = 'Baptized', TRUE, FALSE),
	listed = IF(@listed = 'Unlisted', FALSE, TRUE),
	inactive = IF(@inactive = 'Inactive', TRUE, FALSE),
	how_they_heard = NULLIF(@how_they_heard, ''),
	reason_left_church = NULLIF(@reason_left_church, ''),
	child_work_date_start = STR_TO_DATE(NULLIF(@child_work_date_start, ''), '%b %d, %Y'),
	child_work_date_end = STR_TO_DATE(NULLIF(@child_work_date_end, ''), '%b %d, %Y')
;
